"""create matches table

Revision ID: 70a8d4cbf0d3
Revises: 7d2550058c5b
Create Date: 2026-08-07 12:34:33.021715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a8d4cbf0d3'
down_revision: Union[str, Sequence[str], None] = '7d2550058c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_one_id', sa.Uuid(), nullable=False),
    sa.Column('user_two_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UNMATCHED', 'BLOCKED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('user_one_id <> user_two_id', name='ck_match_users_different'),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uq_match_users')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
