from enum import Enum



class NotificationType(str, Enum):
    LIKE_RECIEVED = "LIKE_RECIEVED"
    MATCH_CREATED = "MATCH_CREATED"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    CHECKIN_REMINDER = "CHECKIN_REMINDER"
    IRL_CONFIRMATION = "IRL_CONFIRMATION"
